-- 
TRUNCATE TABLE Agence RESTART IDENTITY CASCADE;
TRUNCATE TABLE Employe RESTART IDENTITY CASCADE;
TRUNCATE TABLE AgentTechnique CASCADE;
TRUNCATE TABLE AgentCommercial CASCADE;
TRUNCATE TABLE SocieteEntretien CASCADE;
TRUNCATE TABLE AssocAgenceSocieteEntretien CASCADE;
TRUNCATE TABLE Entretien RESTART IDENTITY CASCADE;
TRUNCATE TABLE TypeCarburant CASCADE;
TRUNCATE TABLE Vehicule CASCADE;
TRUNCATE TABLE Location RESTART IDENTITY CASCADE;
TRUNCATE TABLE Particulier RESTART IDENTITY CASCADE;
TRUNCATE TABLE LocationParticulier CASCADE;
TRUNCATE TABLE Entreprise RESTART IDENTITY CASCADE;
TRUNCATE TABLE Conducteur CASCADE;
TRUNCATE TABLE LocationProfessionnel CASCADE;
TRUNCATE TABLE Facturation CASCADE;