-- 
TRUNCATE TABLE Agence RESTART IDENTITY CASCADE;
TRUNCATE TABLE Employe RESTART IDENTITY CASCADE;
TRUNCATE TABLE AgentTechnique CASCADE;
TRUNCATE TABLE TypeCarburant CASCADE;
TRUNCATE TABLE Vehicule CASCADE;