--
DROP TABLE Agence CASCADE;
DROP TABLE Employe CASCADE;
DROP TABLE AgentTechnique CASCADE;
DROP TABLE AgentCommercial CASCADE;
DROP TABLE SocieteEntretien CASCADE;
DROP TABLE AssocAgenceSocieteEntretien CASCADE;
DROP TYPE Resultat_entretien CASCADE;
DROP TABLE Entretien CASCADE;
DROP TABLE TypeCarburant CASCADE;
DROP TABLE Vehicule CASCADE;
DROP TABLE Location CASCADE;
DROP TABLE Particulier CASCADE;
DROP TABLE LocationParticulier CASCADE;
DROP TABLE Entreprise CASCADE;
DROP TABLE Conducteur CASCADE;
DROP TABLE LocationProfessionnel CASCADE;
DROP TABLE Facturation CASCADE;
